"use strict";
const $=s=>document.querySelector(s),app=$("#app"),canvas=$("#canvas"),ctx=canvas.getContext("2d"),scene=$("#scene"),headlineEl=$("#headline"),summaryEl=$("#summary"),categoryEl=$("#category"),kickerEl=$("#kicker"),keywordList=$("#keywordList"),progressBar=$("#progressBar"),composer=$("#composer"),headlineInput=$("#headlineInput"),keywordsInput=$("#keywordsInput"),summaryInput=$("#summaryInput"),wipe=$("#wipe");
let w=0,h=0,dpr=1,particles=[],activeTheme=themes.generic,activeVisual="orbit",start=performance.now(),paused=false,pauseAt=0,pauseOffset=0,demoIndex=0,random=Math.random;const duration=12000;
function hash(s){let v=2166136261;for(let i=0;i<s.length;i++){v^=s.charCodeAt(i);v=Math.imul(v,16777619)}return v>>>0}function rng(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function clean(v){return String(v||"").toLowerCase().normalize("NFKD").replace(/[_/-]+/g," ").replace(/[^a-z0-9.'£%+\s]/g," ").replace(/\s+/g," ").trim()}function count(text,term){term=clean(term);if(!term)return 0;const e=term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/ /g,"\\s+");return(text.match(new RegExp(`(?:^|\\b)${e}(?:\\b|$)`,`g`))||[]).length}
function matchTheme(text){const c=clean(text);let best={key:"generic",score:0,priority:-1};for(const[key,t]of Object.entries(themes)){if(key==="generic")continue;let score=0;(t.phrases||[]).forEach(x=>score+=count(c,x)*16);(t.terms||[]).forEach(x=>score+=count(c,x)*(clean(x).length>7?6:4));(t.combos||[]).forEach(a=>{if(a.every(x=>count(c,x)))score+=18+a.length*3});if(score&&(score>best.score||score===best.score&&(t.priority||0)>best.priority))best={key,score,priority:t.priority||0}}return best.key}
function fallback(text){const c=clean(text),o=["orbit","wave","signal","bloom","grid"];if(/design|creative|craft|art|handmade/.test(c))return"bloom";if(/data|report|analysis|number|metric|research/.test(c))return"grid";if(/fast|launch|boost|surge|update|trend/.test(c))return"signal";if(/calm|dream|soft|ambient|relax/.test(c))return"wave";return o[hash(c)%o.length]}
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);makeParticles()}
function makeParticles(){particles=Array.from({length:Math.min(180,Math.max(70,Math.round(w*h/9500)))},()=>({x:random()*w,y:random()*h,z:.2+random()*1.2,s:.5+random()*4,v:.2+random()*2,a:.08+random()*.55,p:random()*Math.PI*2}))}
function palette(t){const[a,b,c,d]=t.colors;for(const[k,v]of [["--bg-0",a],["--bg-1",b],["--accent",c],["--accent-2",d]])app.style.setProperty(k,v)}
function add(cls,text=""){const e=document.createElement("div");e.className=cls;e.textContent=text;scene.appendChild(e);return e}function buildScene(t,words){scene.replaceChildren();const v=t.visual||"orbit",word=t.motionWord||words[0]||"STORY";if(["tech","space","ai","orbit","grid"].includes(v)){add("ring");add("ring r2");add("orb");add("radar")}if(["sports","travel","signal","breaking"].includes(v)){add("emoji",t.emoji);const wrap=add("speed-lines");for(let i=0;i<22;i++){const l=document.createElement("div");l.className="speed-line";l.style.setProperty("--top",random()*100+"%");l.style.setProperty("--delay",-random()*1.1+"s");wrap.appendChild(l)}}if(["nature","bloom"].includes(v)){for(let i=0;i<5;i++){const l=add("leaf");l.style.setProperty("--rot",(-60+i*30)+"deg");l.style.setProperty("--x",(-18+i*9)+"vw");l.style.setProperty("--scale",.65+random()*.5);l.style.setProperty("--delay",i*.12+"s")}}if(["wave","generic","food","fashion"].includes(v))add("emoji",t.emoji);add("flash-word",word)}
function rgba(hex,a){hex=hex.replace("#","");const n=parseInt(hex.length===3?[...hex].map(x=>x+x).join(""):hex,16);return`rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}
function background(t){ctx.clearRect(0,0,w,h);const a=activeTheme.colors[2],b=activeTheme.colors[3],gx=w*(.5+Math.sin(t*.00018)*.08),gy=h*(.36+Math.cos(t*.00016)*.06),g=ctx.createRadialGradient(gx,gy,0,gx,gy,Math.max(w,h)*.72);g.addColorStop(0,rgba(a,.2));g.addColorStop(.4,rgba(b,.06));g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);if(["rain","drizzle","thunder","sleet","hail"].includes(activeVisual))rain(t,b);else if(["snow","cold"].includes(activeVisual))snow(t,b);else if(activeVisual==="fog")fog(t,b);else if(["sports","travel","signal","breaking","wind"].includes(activeVisual))rush(b);else if(activeVisual==="finance")market(t,a,b);else if(["nature","bloom"].includes(activeVisual))nature(t,b);else if(activeVisual==="wave")waves(t,a,b);else if(activeVisual==="grid")grid(t,a,b);else if(activeVisual==="ai")network(t,a,b);else stars(t,a,b)}
function stars(t,a,b){particles.forEach((p,i)=>{p.y-=p.v*p.z*.18;p.x+=Math.sin(t*.0004+p.p)*.08;if(p.y<-10){p.y=h+10;p.x=random()*w}ctx.beginPath();ctx.fillStyle=i%5?`rgba(255,255,255,${p.a})`:rgba(i%2?a:b,p.a);ctx.arc(p.x,p.y,p.s*p.z,0,7);ctx.fill()})}
function rain(t,b){particles.forEach((p,i)=>{p.x+=2;p.y+=5+p.v*5;if(p.y>h+40){p.y=-40;p.x=random()*w}ctx.beginPath();ctx.strokeStyle=i%7?`rgba(220,240,255,${p.a})`:rgba(b,.7);ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+8,p.y+28);ctx.stroke()});if(activeVisual==="thunder"&&Math.sin(t*.004)>.996){ctx.fillStyle="rgba(255,255,255,.18)";ctx.fillRect(0,0,w,h)}}
function snow(t,b){particles.forEach(p=>{p.y+=.4+p.v*.5;p.x+=Math.sin(t*.0007+p.p)*.5;if(p.y>h+10)p.y=-10;ctx.beginPath();ctx.fillStyle=rgba(b,p.a);ctx.arc(p.x,p.y,p.s+1,0,7);ctx.fill()})}
function fog(t,b){for(let i=0;i<8;i++){const x=(t*.02+i*w/6)%(w*1.4)-w*.2,y=h*(.18+i*.09);const g=ctx.createRadialGradient(x,y,0,x,y,w*.3);g.addColorStop(0,rgba(b,.1));g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}}
function rush(b){particles.forEach(p=>{p.x+=4+p.v*4;if(p.x>w+60)p.x=-60;ctx.beginPath();ctx.strokeStyle=rgba(b,p.a);ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-30-p.v*12,p.y);ctx.stroke()})}
function market(t,a,b){ctx.beginPath();for(let i=0;i<=50;i++){const x=i/50*w,y=h*.5-i/50*h*.18+Math.sin(i*.7+t*.001)*18;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=rgba(b,.85);ctx.lineWidth=4;ctx.stroke();stars(t,a,b)}
function nature(t,b){particles.forEach(p=>{p.y-=p.v*.25;p.x+=Math.sin(t*.0005+p.p)*.4;if(p.y<0)p.y=h;ctx.fillStyle=rgba(b,p.a);ctx.beginPath();ctx.ellipse(p.x,p.y,p.s*2,p.s,0,0,7);ctx.fill()})}
function waves(t,a,b){for(let i=0;i<7;i++){ctx.beginPath();for(let x=0;x<=w;x+=12){const y=h*(.22+i*.085)+Math.sin(x*.012+t*.0013+i)*15;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=rgba(i%2?a:b,.14+i*.05);ctx.lineWidth=2;ctx.stroke()}}
function grid(t,a,b){const s=Math.max(34,w/14);for(let x=0;x<w;x+=s)for(let y=0;y<h;y+=s){const q=.3+(Math.sin(t*.0014+x*.02+y*.015)+1)/2;ctx.fillStyle=rgba((x+y)%2?a:b,.18*q);ctx.beginPath();ctx.arc(x,y,1+q*3,0,7);ctx.fill()}}
function network(t,a,b){stars(t,a,b);const cx=w/2,cy=h*.42;for(let i=0;i<12;i++){const q=i/12*Math.PI*2+t*.0002,r=Math.min(w,h)*(.13+(i%3)*.04),x=cx+Math.cos(q)*r,y=cy+Math.sin(q)*r*.7;ctx.strokeStyle=rgba(i%2?a:b,.4);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle=rgba(i%2?b:a,.9);ctx.beginPath();ctx.arc(x,y,4+i%3,0,7);ctx.fill()}}
function render(data,transition=true){const headline=(data.headline||"A story worth seeing").trim(),raw=(data.keywords||"news, story, motion").trim(),summary=(data.summary||"A full-screen animation generated from the story context.").trim(),words=raw.split(",").map(x=>x.trim()).filter(Boolean).slice(0,8),combined=`${headline} ${headline} ${raw} ${summary}`,key=matchTheme(combined),theme=themes[key]||themes.generic;random=rng(hash(combined));activeTheme=theme;activeVisual=key==="generic"?fallback(combined):theme.visual||"orbit";palette(theme);const commit=()=>{headlineEl.textContent=headline;summaryEl.textContent=summary;categoryEl.textContent=theme.label;kickerEl.textContent=theme.kicker;keywordList.innerHTML=words.map(x=>`<span class="keyword">${escapeHtml(x)}</span>`).join("");buildScene({...theme,visual:activeVisual},words);makeParticles();start=performance.now()-pauseOffset};if(transition){wipe.classList.remove("play");void wipe.offsetWidth;wipe.classList.add("play");setTimeout(commit,350)}else commit();const p=new URLSearchParams(location.search);p.set("headline",headline);p.set("keywords",raw);p.set("summary",summary);history.replaceState(null,"",`${location.pathname}?${p}`)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function tick(now){if(!paused){const t=now-pauseOffset;background(t);progressBar.style.width=((t-start)%duration)/duration*100+"%"}requestAnimationFrame(tick)}
function openEditor(){headlineInput.value=headlineEl.textContent;keywordsInput.value=[...keywordList.children].map(x=>x.textContent).join(", ");summaryInput.value=summaryEl.textContent;composer.classList.add("open")}function toggle(){paused=!paused;app.classList.toggle("paused",paused);if(paused)pauseAt=performance.now();else pauseOffset+=performance.now()-pauseAt}
$("#editBtn").onclick=openEditor;$("#cancelBtn").onclick=()=>composer.classList.remove("open");$("#generateBtn").onclick=()=>{render({headline:headlineInput.value,keywords:keywordsInput.value,summary:summaryInput.value});composer.classList.remove("open")};$("#nextBtn").onclick=()=>{demoIndex=(demoIndex+1)%demos.length;render(demos[demoIndex])};$("#pauseBtn").onclick=toggle;addEventListener("resize",resize);addEventListener("keydown",e=>{if(e.key==="Escape")composer.classList.remove("open");if(e.key==="ArrowRight")$("#nextBtn").click()});const p=new URLSearchParams(location.search);resize();render({headline:p.get("headline")||demos[0].headline,keywords:p.get("keywords")||demos[0].keywords,summary:p.get("summary")||demos[0].summary},false);requestAnimationFrame(tick);
