Object.assign(themes, {
  parenting:{label:"Family",kicker:"Life through a family lens",colors:["#180b12","#4f1d36","#f472b6","#fbcfe8"],emoji:"👨‍👩‍👧",terms:["parenting","parent","family","child","children","kid","kids","baby","toddler","mother","father"],phrases:["family life","child development","baby sleep"],visual:"bloom",priority:5,motionWord:"FAMILY"},
  education:{label:"Education",kicker:"Learning brought to life",colors:["#071126","#172e62","#3b82f6","#bfdbfe"],emoji:"🎓",terms:["education","school","teacher","student","university","college","learning","lesson","exam","gcse"],phrases:["primary school","secondary school","exam results"],visual:"grid",priority:5,motionWord:"LEARN"},
  football:{label:"Football",kicker:"Built for the big moment",colors:["#061408","#17401d","#84cc16","#fef08a"],emoji:"⚽",terms:["football","soccer","goal","striker","goalkeeper","transfer","fixture"],phrases:["premier league","champions league","penalty shootout"],visual:"sports",priority:9,motionWord:"GOAL"},
  sports:{label:"Sport",kicker:"Built for the big moment",colors:["#07160b","#114726","#84cc16","#fef08a"],emoji:"🏆",terms:["sport","sports","match","player","team","league","cup","win","score","stadium","boxing","tennis","rugby","cricket","racing"],phrases:["world cup","final score","gold medal"],visual:"sports",priority:3,motionWord:"WIN"},
  travel:{label:"Travel",kicker:"A story with momentum",colors:["#051625","#0e4f64","#2dd4bf","#fde68a"],emoji:"✈️",terms:["travel","flight","holiday","tourism","destination","airport","journey","trip","hotel","beach","passport","airline"],phrases:["travel advice","flight delay","city break"],visual:"travel",priority:5,motionWord:"GO"},
  transport:{label:"Transport",kicker:"How the world keeps moving",colors:["#07131b","#173b50","#06b6d4","#cffafe"],emoji:"🚆",terms:["transport","train","rail","railway","bus","tube","traffic","road","commute","station","cycling"],phrases:["rail disruption","road closure","public transport"],visual:"travel",priority:7,motionWord:"MOVE"},
  food:{label:"Food",kicker:"Made to look delicious",colors:["#1b0804","#5b1c0d","#fb923c","#fde68a"],emoji:"🍜",terms:["food","restaurant","chicken","burger","pizza","recipe","meal","coffee","drink","kitchen","chef","baking","cooking"],phrases:["street food","new restaurant","food review"],visual:"bloom",priority:5,motionWord:"TASTE"},
  fashion:{label:"Fashion",kicker:"Style takes centre stage",colors:["#170812","#4c1535","#ec4899","#fbcfe8"],emoji:"👗",terms:["fashion","style","clothing","outfit","designer","catwalk","runway","dress","shoes","streetwear","beauty","makeup"],phrases:["fashion week","new collection","beauty routine"],visual:"bloom",priority:6,motionWord:"STYLE"},
  shopping:{label:"Shopping",kicker:"Products with momentum",colors:["#101007","#3f3a16","#eab308","#fef9c3"],emoji:"🛍️",terms:["shopping","shop","retail","sale","deal","discount","offer","product","supermarket","store"],phrases:["black friday","price drop","new product"],visual:"finance",priority:4,motionWord:"DEAL"},
  music:{label:"Music",kicker:"Sound becomes motion",colors:["#16051a","#4a0d58","#d946ef","#67e8f9"],emoji:"🎵",terms:["music","song","album","singer","rapper","band","concert","tour","festival","spotify","chart"],phrases:["new album","new single","music festival"],visual:"wave",priority:7,motionWord:"SOUND"},
  entertainment:{label:"Entertainment",kicker:"Made for the spotlight",colors:["#170617","#4a0b45","#ec4899","#f9a8d4"],emoji:"🎬",terms:["movie","film","cinema","television","tv","series","actor","director","netflix","celebrity","show","viral","influencer"],phrases:["box office","tv series","red carpet","reality show"],visual:"signal",priority:5,motionWord:"ACTION"},
  culture:{label:"Culture",kicker:"Ideas, identity and creativity",colors:["#140c08","#4a2b18","#f59e0b","#fed7aa"],emoji:"🎭",terms:["culture","art","museum","gallery","theatre","book","author","history","heritage","festival","craft","handmade","design"],phrases:["art exhibition","new book","cultural festival"],visual:"bloom",priority:5,motionWord:"CREATE"},
  climate:{label:"Climate",kicker:"The planet is the headline",colors:["#06140c","#17402b","#22c55e","#a7f3d0"],emoji:"🌍",terms:["climate","emissions","carbon","pollution","sustainability","net-zero"],phrases:["climate change","global warming","net zero"],visual:"nature",priority:8,motionWord:"PLANET"},
  nature:{label:"Nature",kicker:"Growth you can feel",colors:["#06140c","#163f28","#22c55e","#d9f99d"],emoji:"🌿",terms:["nature","green","tree","forest","plant","garden","environment","earth","river","ocean","wildlife","animal"],phrases:["natural world","green space","urban forest"],visual:"nature",priority:4,motionWord:"GROW"},
  ai:{label:"AI",kicker:"Synthetic intelligence in motion",colors:["#050814","#111a3d","#7c3aed","#22d3ee"],emoji:"🤖",terms:["ai","genai","llm","llms","chatgpt","gpt","openai","anthropic","gemini","claude","ollama","copilot","agent","agents","automation","neural","inference","prompt","ml"],phrases:["artificial intelligence","large language model","language model","ai assistant","ai agents","generative ai","machine learning","neural network"],visual:"ai",priority:12,motionWord:"AI"},
  robotics:{label:"Robotics",kicker:"Machines learning to move",colors:["#05070e","#1b2336","#60a5fa","#a78bfa"],emoji:"🦾",terms:["robot","robots","robotic","robotics","android","humanoid","drone","autonomous"],phrases:["humanoid robot","robot assistant","robotic arm"],visual:"ai",priority:11,motionWord:"ROBOTS"},
  generic:{label:"Visual Story",kicker:"Keyword-generated motion",colors:["#070912","#11152a","#8b5cf6","#22d3ee"],emoji:"✦",terms:[],phrases:[],visual:"orbit",priority:-1,motionWord:"STORY"}
});
